# Generated by Django 4.2.25 on 2025-10-31 01:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.member')),
            ],
        ),
    ]
