# Generated by Django 4.2.25 on 2025-10-31 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_book_alter_loan_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
